site_name: Wiki 585 Видеостудии

theme:
  name: material
  language: ru
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.action.edit
    - content.tabs.link

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes

nav:
  - Главная: index.md
  - Камеры:
      - Обзор: cameras/index.md
      - Sony FX3: cameras/sony_fx3.md
  - Свет:
      - Обзор: lighting/index.md
      - Схемы света: lighting/basic_setups.md
  - Звук:
      - Рекордеры: audio/recorders.md
  - Чек-листы:
      - Перед съёмкой: checklists/pre_shoot.md